from datetime import date, datetime
from typing import Optional

from sqlalchemy import (
    Boolean, Date, DateTime, Float, Integer, String, Text,
    UniqueConstraint, Index,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class CreativeAnalysis(Base):
    """Claude's analysis of a Facebook ad creative."""

    __tablename__ = "creative_analyses"
    __table_args__ = (
        Index("ix_creative_analysis_ad", "ad_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    ad_id: Mapped[str] = mapped_column(String(64), nullable=False)
    analyzed_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    model_used: Mapped[str] = mapped_column(String(64))

    # Scores 0-10
    hook_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    copy_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    visual_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    offer_clarity_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    overall_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Narrative analysis
    hook_analysis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    copy_analysis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    visual_analysis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    full_diagnosis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    improvement_suggestions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Transcript (for video ads)
    video_transcript: Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class PlatformInsight(Base):
    """
    Cross-platform insights generated by Claude.
    Examples:
      - High FB CTR + high cart abandonment → landing page problem
      - High frequency + dropping CTR → creative fatigue
      - Good ROAS + low LTV → not acquiring new customers
    """

    __tablename__ = "platform_insights"
    __table_args__ = (
        Index("ix_platform_insight_type", "insight_type"),
        Index("ix_platform_insight_generated", "generated_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    # "creative_fatigue" | "landing_page" | "ltv_risk" | "scaling_opportunity" | etc.
    insight_type: Mapped[str] = mapped_column(String(64), nullable=False)
    # "info" | "warning" | "critical"
    severity: Mapped[str] = mapped_column(String(16), default="info")
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # Comma-separated ad_ids involved (if applicable)
    related_ad_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False)


class AttributionSnapshot(Base):
    """
    Tracks the discrepancy between Facebook's reported conversions
    and Shopify's actual orders for the same period.
    Facebook uses 7-day click / 1-day view attribution by default.
    This table makes the gap visible and explainable.
    """

    __tablename__ = "attribution_snapshots"
    __table_args__ = (
        UniqueConstraint("ad_id", "snapshot_date", name="uq_attribution_ad_date"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    ad_id: Mapped[str] = mapped_column(String(64), nullable=False)
    snapshot_date: Mapped[date] = mapped_column(Date, nullable=False)

    # What Facebook claims
    fb_reported_purchases: Mapped[int] = mapped_column(Integer, default=0)
    fb_reported_roas: Mapped[float] = mapped_column(Float, default=0)
    fb_spend: Mapped[float] = mapped_column(Float, default=0)

    # What Shopify shows for same date range
    shopify_orders: Mapped[int] = mapped_column(Integer, default=0)
    shopify_revenue: Mapped[float] = mapped_column(Float, default=0)
    shopify_roas: Mapped[float] = mapped_column(Float, default=0)

    # discrepancy_pct = (fb_roas - shopify_roas) / shopify_roas * 100
    discrepancy_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
